version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:12.5
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - "5432:5432"

  superset:
    image: apache/superset
    depends_on:
      - db
      - redis
    ports:
      - "8088:8088"
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./config/superset_config.py:/app/superset/superset_config.py
